# Use ubuntu as the base image
FROM ubuntu:latest

# Install curl
RUN apt-get update && apt-get install -y curl

# Set a default command to print a message
CMD ["echo", "Hello from my custom image for Docker!"]
